### ISSUE TITLE
Video without audio being treated as an image

### ISSUE THREAD

**Issue by Rob--** [agermanidis/SnapchatBot#12]
I noticed that it's possible to send and open images and videos with no problem.
However, it is possible to disable audio on Android and on iOS you can disable the microphone from the Settings applications which denies Snapchat microphone access when recording.

I don't have the error message saved, I could get it if need be.
I was looking through the library to try an resolve this error, I noticed when a new Snap is created it passes along the `MEDIA_TYPE`. During this process of creating the Snap object you try and decide whether it's an image or a video. This works fine, apart form the fact that there's two types of videos. Videos with and without audio.

During the process of creating a snap you only check to see if it's a `MEDIA_TYPE_VIDEO`, you never check `MEDIA_TYPE_VIDEO_WITHOUT_AUDIO`. Therefore a video without audio results in being treated as an image in the else statement of this check.

In snap.py, line 64:

    64: if self.media_type is MEDIA_TYPE_VIDEO:
    65:     self.file.write(opts['data'])
    66:     self.file.flush()
    67:
    68: else:
    69:     image = Image.open(StringIO(opts['data']))
    70:     resize_image(image, self.file.name)

It checks if it's `MEDIA_TYPE_VIDEO`, however `MEDIA_TYPE_VIDEO_WITHOUT_AUDIO` has it's own constant separate from `MEDIA_TYPE_VIDEO` and therefore if a Snap contains a video without audio it will resort to being treated as an image.

I'm not sure how this hasn't been spotted before, so I've had to change line 64:

before:

     if self.media_type is MEDIA_TYPE_VIDEO:

after:

     if self.media_type is MEDIA_TYPE_VIDEO or MEDIA_TYPE_VIDEO_WITHOUT_AUDIO:

you also need to import this constant, so line 6 needs to be changed:

before:

    from constants import MEDIA_TYPE_IMAGE, MEDIA_TYPE_VIDEO, DEFAULT_DURATION, SNAP_IMAGE_DIMENSIONS

after:

    from constants import MEDIA_TYPE_IMAGE, MEDIA_TYPE_VIDEO, MEDIA_TYPE_VIDEO_WITHOUT_AUDIO, DEFAULT_DURATION, SNAP_IMAGE_DIMENSIONS

**Comment by agermanidis** [comment]
Good catch, I pushed a fix.
