### ISSUE TITLE
Question about deleting story segments or entire story

### ISSUE THREAD

**Issue by ShaneIsrael** [agermanidis/SnapchatBot#17]
Is there a way to have the bot delete the oldest story segments? I had a bot reach what I think was the max story of 4950 seconds and get Forbidden errors when trying to post further and thus needed to wait 24 hours for it to clear. 

Thanks

**Comment by agermanidis** [comment]
Yes, I just need to implement the method on `SnapchatBot` that calls `/bq/delete_story`, will get on that soon

**Comment by ShaneIsrael** [comment]
Awesome thank you!

**Comment by ShaneIsrael** [comment]
One other question related to the story. Do you have any idea why I might occasionally be getting a "403 Forbidden Error" when trying to post to the story. It happens fairly frequently and causes the bot to crash. I noticed it only started happening after the bot started posting quite a lot to the story. But even after letting the story refresh it is continuing to happen frequently. Possibly Snapchat limiting the accounts allowed post frequency?

**Comment by agermanidis** [comment]
That's likely Snapchat blocking your IP/account. Try to increase the timeout on the `listen` method.

**Comment by N07070** [comment]
Up to implement this ! :+1:

**Comment by agermanidis** [comment]
I added a `delete_story` method on `SnapchatBot`. My IP has been temporarily blocked by Snapchat right now, so I didn't have time to fully test this, but let me know if you encounter any issues.

**Comment by N07070** [comment]
Awesome !
