### ISSUE TITLE
Error when getting a video from a friend.

### ISSUE THREAD

**Issue by N07070** [agermanidis/SnapchatBot#18]
```
Traceback (most recent call last):
  File "storyfbbot-dev.py", line 40, in <module>
    bot.listen()
  File "/home/n07070/Code/SnapchatBot/snapchat_bots/bot.py", line 54, in listen
    self.on_snap(snap.sender, snap)
  File "storyfbbot-dev.py", line 26, in on_snap
    self.post_story(snap)
  File "/home/n07070/Code/SnapchatBot/snapchat_bots/bot.py", line 101, in post_story
    snap.upload(self)
  File "/home/n07070/Code/SnapchatBot/snapchat_bots/snap.py", line 40, in upload
    self.media_id = bot.client.upload(self.file.name)
  File "build/bdist.linux-i686/egg/pysnap/__init__.py", line 353, in upload
ValueError: Could not determine media type for given data
```

I'm trying to fix it. Could use a little help :wink: 
Edit: Works with the iPhone 6, but not with Android Phones ( OnePlus One )

`Traceback (most recent call last):
  File "./storyfbbot-dev.py", line 40, in <module>
    bot.listen()
  File "/home/n07070/Code/SnapchatBot/snapchat_bots/bot.py", line 54, in listen
    self.on_snap(snap.sender, snap)
  File "./storyfbbot-dev.py", line 26, in on_snap
    self.post_story(snap)
  File "/home/n07070/Code/SnapchatBot/snapchat_bots/bot.py", line 101, in post_story
    snap.upload(self)
  File "/home/n07070/Code/SnapchatBot/snapchat_bots/snap.py", line 40, in upload
    self.media_id = bot.client.upload(self.file.name)
  File "build/bdist.linux-i686/egg/pysnap/__init__.py", line 353, in upload
ValueError: Could not determine media type for given data
`

**Comment by jackbillstrom** [comment]
I actually got get a video from a friend, but I couldn't open it. Seems like it's broken.

``Mac OS X 10.10.2``

**Comment by N07070** [comment]
You sent a video from a Mac ?

**Comment by jackbillstrom** [comment]
@N07070  No, sorry I meant that I'm running on a Mac

**Comment by N07070** [comment]
Could you try to run it on another system ( windows,linux,bsd ? )

**Comment by jackbillstrom** [comment]
@N07070 I recieved it, and saved it. I could try running it on linux within the next hour I believe.

**Comment by N07070** [comment]
Could not reproduce with my OnePlus. Assuming it's fixed ? I will try with another phone. 
@jackbillstrom , it could be cool. Also, can you send snaps to the bot, that will then repost it or send it to another friend ? ( Like with the reflector or stroryfier bot ? )

**Comment by jackbillstrom** [comment]
@N07070 Haven't tried those yet,  just modified the ``autowelcomebot.py``with my needs. I'll try and report.

**Comment by Rob--** [comment]
@N07070 - yes, of course, why wouldn't you be able to? You could also pick a random person from your friends list to send it to.

**Comment by N07070** [comment]
I was actually more geunily curious, but it is true that a random snap service would be pretty neat. A thing a bit like Fling.

**Comment by ShaneIsrael** [comment]
My bot will crash with the exact error same error if either myself (Nexus 4) or two of my friends (iPhone 5) send it any form of video. However, other people (I don't know the device or snapchat version) have successfully sent it a video.

**Comment by N07070** [comment]
Seems to be an error with the determination of media type ( which is strange, cause it's supposed to be all .mp4 )

**Comment by N07070** [comment]
Up, I'm still getting the error. It seems to come from pysnap, so I would like to update pysnap to do that. Is it possible ? Could we update to using the last version of pysnap ?

**Comment by Rob--** [comment]
I can't look into this now, but it might be worth cloning the library, edit some code involved with retrieving the file type and then installing that library.

**Comment by Sh1eld** [comment]
PIL and ImageMagick installed? Only thing I can think of because I am not having this issue and I have both of these installed.

**Comment by ShaneIsrael** [comment]
I have both of those installed and still get the issue.

**Comment by agermanidis** [comment]
> Works with the iPhone 6, but not with Android Phones

I think that might be key. Snapchat for Android might be sending the data of the snap gzipped, unlike the iOS version which sends raw data. `SnapchatBot` is not handling the gzipped case right now. I'll add code to unzip the data and then process it in a bit.

**Comment by agermanidis** [comment]
To those who are encountering this issue: what phone are the snaps you're trying to process being sent from?

@N07070 @jackbillstrom @ShaneIsrael

**Comment by N07070** [comment]
@agermanidis do you think you could get an android phone for a few days to test ? I could provide a small, old, galaxy Y phone.

**Comment by ShaneIsrael** [comment]
I have an android phone and I could test, however for some reason I am
getting a 400 Client Error: Bad Request when trying to run my bot from my
computer. However, I can log into it connected to my wifi from my phone
so I'm not sure what the problem is there. Wasn't an issue yesterday or
previous days.

**Comment by N07070** [comment]
It seems that it's an error with our IPs being banned.

**Comment by ShaneIsrael** [comment]
That doesn't make sense though. I have the exact same IP address on my
phone and can log into it on my phone just fine.

I looked up 400 Client Error and it has something to do with sending the
log in info in an unrecognized format. I wonder if
Snapchat made a change on their end.

**Comment by N07070** [comment]
Fixed. Okay, but the issue is still not fixed with videos :smile:

**Comment by Rob--** [comment]
If you have a look at the open issue about a 400 Bad Request error you can follow the updates on the situation, basically Snapchat have most likely tried pushing users to `loq` (as logging in with this part of the API requires more tokens and is somewhat securer). I'm currently recreating this library to work with all of the latest API's endpoints.

**Comment by ShaneIsrael** [comment]
Awesome thank you! Can't wait until the videos are working. Thanks for the
quick response! :)

**Comment by Rob--** [comment]
The videos should be working - right now I've got I've got a bot running on a server that can handle videos. If you provide me with more information, I can try and solve the issue if I have time tomorrow.

**Comment by ShaneIsrael** [comment]
All I know is that when I (Android (lollipop) nexus 4) or my friends on
iPhone 5's and 5s's send videos to the bot, it crashes with the error being
unable to identify media type. (I have imageshack and ffmpeg installed).
However, some people (don't know who they are) are able to get videos
through occasionally without crashing the bot. No idea what phones they
have.

**Comment by N07070** [comment]
It seems to be very random, sometimes it's okay, sometimes no...

```
Traceback (most recent call last):
  File "./storyfbbot-dev.py", line 40, in <module>
    bot.listen()
  File "SnapchatBot/snapchat_bots/bot.py", line 66, in listen
    self.on_snap(snap.sender, snap)
  File "./storyfbbot-dev.py", line 26, in on_snap
    self.post_story(snap)
  File "/SnapchatBot/snapchat_bots/bot.py", line 113, in post_story
    snap.upload(self)
  File "SnapchatBot/snapchat_bots/snap.py", line 40, in upload
    self.media_id = bot.client.upload(self.file.name)
  File "build/bdist.linux-i686/egg/pysnap/__init__.py", line 353, in upload
ValueError: Could not determine media type for given data
```

**Comment by feedthedogs** [comment]
I am getting the same issue, I tried saving the file and the images work but the videos come out as 0 bytes, it could be the zip issue, but it looks like pysnap takes care of that?

**Comment by PhlexPlexico** [comment]
I have the same issue happening with me. I'm able to send videos without text on the screen. However, if there is no text it sends just fine. Using SnapPrefs on android, I do believe the video and text are saved as separate files. I.e. the videos are saved as MP4s, and the text is saved as a jpg. Could this perchance be the problem?

**Comment by Rob--** [comment]
@feedthedogs I had the same issue with saving files, I found another simpler solution (only three lines).

Python has a handy library called `pdb`. You can import it and call `pdb.set_trace()`. This will allow you step through your code and debug it line by line (after `set_trace()` is called, type `n` and press enter in the console to step over the code). I suggest downloading this library, setting a few traces around functions where you think the error could be caused and then installing your now customised library. This will allow you to identify exactly where the error is occurring. You can also call variables to print them out (just type the variable name and press enter).

**Comment by N07070** [comment]
* iPhone 6 : 
    * Video Snap without text :heavy_check_mark: 
    * with text :no_entry_sign: 
* OnePlus One ( Lollipop ) : 
    * Without text :heavy_check_mark: 
    * With text :no_entry_sign:

**Comment by PhlexPlexico** [comment]
@N07070 that being said with the snaps being sent as both jpeg and mp4, any ideas how these are sent over Snapchat? As previously commented, are they gzipped then sent to be extracted on the client end? Would it be possible to redirect the entire snap somehow without the api touching it and separating the text jpg and the mp4? I haven't poked around much in the library, and plan to look more in the coming weeks as this is a very interesting library to work with.

**Comment by N07070** [comment]
I really don't have the competence to help out with this, sorry man...

**Comment by ishaantaylor** [comment]
I'm also having an issue saving any videos at all (they come up as 0 bytes). These have been sent from a variety of phones. Generally, I can manipulate the snaps even if they are videos. However, there was one error with a Galaxy S3 that the bot was crashing when it tried to send it a video. (This doesn't happen any more.) 

Additionally, how would you suggest updating the library so it is up to date with the master branch here? Would a `git pull` then `python setup.py install` work? Or should I uninstall it first?

**Comment by N07070** [comment]
So, for me, it's just when there is texte added. 
To update, I just do a git pull. 

Le 10 mars 2015 12:11:10 GMT+01:00, Ishaan Taylor <notifications@github.com> a écrit :
>I'm also having an issue saving any videos at all (they come up as 0
>bytes). These have been sent from a variety of phones. Generally, I can
>manipulate the snaps even if they are videos. However, there was one
>error with a Galaxy S3 that the bot was crashing when it tried to send
>it a video. (This doesn't happen any more.) 
>
>Additionally, how would you suggest updating the library so it is up to
>date with the master branch here? Would a `git pull` then `python
>setup.py install` work? Or should I uninstall it first?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/agermanidis/SnapchatBot/issues/18#issuecomment-78034197

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by PhlexPlexico** [comment]
@agermanidis has there been any progress to this? Any idea if another pysnap library has figured out this issue? I'm still getting it on my end.

**Comment by Rob--** [comment]
@PhlexPlexico, my library can 'save' snaps. When downloading a snap a temporary file is made, my `save_snap` method just copies this file to a given directory. Check out my library for the method.

**Comment by N07070** [comment]
If you save snaps, you juste repost it using the Snap.from_file() method ?

**Comment by Rob--** [comment]
What do you mean?

**Comment by krissrex** [comment]
I think he means: 
> If you save a snap, do you just repost it by using the method Snap.from_file(saved_snap)

**Comment by N07070** [comment]
Yes, indeed.

**Comment by krissrex** [comment]
I  believe the error exists in pysnap, and not in SnapchatBot. To be exact, it is this function in _\_\_init.py\_\__
```python
def is_video(data):
    return len(data) > 1 and data[0:2] == b'\x00\x00'
```

My guess is that the byte matching fails. When I print the bytes of two random video tempfiles, they start like this:
<code>504b030414</code>
<code>504b030414</code>
Which obviously fails the check, as the 2 first bytes are not <code>0x00 0x00</code>, but rather <code>0x50 0x4B</code>.

**Comment by agermanidis** [comment]
Can you send me the file (see email in profile) so I can test some code against it? Phone is having camera issues so I can't generate a test video snap with a caption right now.

**Comment by krissrex** [comment]
I will do that. Pysnap needs to be changed several places; first it needs to detect zip as video, then it needs to set the zipped-value to 1 in the json-request when the file is a zip.

**Comment by N07070** [comment]
Will it be updated soon ? How could I help you ?

**Comment by krissrex** [comment]
The file uploaded from android is indeed a .zip. Also, it has type 2 when the video is muted, and type 1 when it is normal. So a videosnap with text is a zip with a type that matches its video.
In the POST to /loq/send, it has the field "zipped" set to 1.

**Comment by agermanidis** [comment]
I'm working on supporting captions generally, both in incoming snaps (with
the text being OCR'ed and available to the user), and in creating new snaps
to send. Will release soon.

The "zipped" field doesn't really matter, it's easy to detect whether data
is zipped or not (from the first bytes). The zip file just contains the
video and a jpg text overlay.

On Sun, Mar 15, 2015 at 8:52 PM, Kristian Rekstad <notifications@github.com>
wrote:

> The file uploaded from android is indeed a .zip. Also, it has type 2 when
> the video is muted, and type 1 when it is normal. So a videosnap with text
> is a zip with a type that matches its video.
> In the POST to /loq/send, it has the field "zipped" set to 1.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agermanidis/SnapchatBot/issues/18#issuecomment-81315456>
> .
>



-- 
Anastasis Germanidis
(860) 807-5860

**Comment by ShaneIsrael** [comment]
I have a bot that I have been coding on for a while to do a bunch of different things. I can sent it commands via the text on the image and it will do stuff based on the commands received. I'm using the tesseract OCR library to parse the text.

**Comment by bl3ndom** [comment]
I think that this crash got something to do with this.
[2015-03-17 03:39:23,004] "POST /bq/blob HTTP/1.1" 200 1078048
Traceback (most recent call last):
  File "storifierbot.py", line 17, in <module>
    bot.listen()
  File "build/bdist.linux-x86_64/egg/snapchat_bots/bot.py", line 62, in listen
  File "build/bdist.linux-x86_64/egg/snapchat_bots/bot.py", line 172, in get_snaps
  File "build/bdist.linux-x86_64/egg/snapchat_bots/bot.py", line 146, in process_snaps
  File "build/bdist.linux-x86_64/egg/snapchat_bots/bot.py", line 53, in process_snap
  File "build/bdist.linux-x86_64/egg/snapchat_bots/snap.py", line 93, in __init__
IOError: File not open for writing

After logging in from phone and watching video-snap, everything works.

Im using CentOS 7, installed today.

**Comment by krissrex** [comment]
That is a separate issue, @bl3ndom. Try running again with sudo.

**Comment by krissrex** [comment]
@bl3ndom This is a different issue. Try running it with sudo.

**Comment by krissrex** [comment]
@agermanidis my comment regarding the zipped field was for uploading to snapchat's servers. Uploading requires some changes to pysnap. I believe [this](https://github.com/krissrex/pysnap/commit/3b620034839fbd14670cb6aeffd49f35da2d03f6) is sufficient, but I have not tested it yet.

**Comment by N07070** [comment]
Is this fixed if I use your pysnap version then ? Because when I save the snap, being a video, I get a 0 bit file... Then, ffmpeg gives me the following error : `temporaire.mp4: Invalid data found when processing input`

**Comment by krissrex** [comment]
My pysnap is not enough. You also need to implement the change in SnapchatBot. ffmpeg needs the mp4 inside the zip, so you must make sure it is extracted. I believe this have been implemented now by Agetmanidis, but I may be wrong.
