### ISSUE TITLE
Newly added people are unable to see previosly added story-snaps

### ISSUE THREAD

**Issue by larserikfagernaes** [agermanidis/SnapchatBot#30]
When a person adds my bot, he is not able to see snaps that are already posted on my bot's story. 
Snapchat normally doens't function like this. Is there a solution for this?

**Comment by ricoxor** [comment]
Set the setting og the account to :
- Everebody can see my story

**Comment by Sh1eld** [comment]
@ricoxor I think that doesn't help though.
I had this issue as well and I'm sure I had that option configured. I think say, I post something to my story, and then someone adds me, they can't see what I posted because it was pre-add. I think this is an intentional feature but I'm just assuming.

**Comment by agermanidis** [comment]
What @ricoxor said is correct!
