### ISSUE TITLE
Error when using capturebot

### ISSUE THREAD

**Issue by N07070** [agermanidis/SnapchatBot#31]
Hello, thanks for the last update !

However, I am now having this issue. 

```
Traceback (most recent call last):
  File "examples/capturebot.py", line 16, in <module>
    bot.listen(timeout=60)
  File "build/bdist.linux-x86_64/egg/snapchat_bots/bot.py", line 65, in listen
  File "examples/capturebot.py", line 6, in on_snap
    snap.save()
  File "build/bdist.linux-x86_64/egg/snapchat_bots/snap.py", line 52, in save
NameError: global name 'filename' is not defined
```

Possible fix: declare `filename =  default_filename_for_snap(snap)`

Thanks !

**Comment by agermanidis** [comment]
Try now?

On Mon, Mar 9, 2015 at 1:55 PM, N07070 <notifications@github.com> wrote:

> Hello, thanks for the last update !
>
> However, I am now having this issue.
>
> Traceback (most recent call last):
>   File "examples/capturebot.py", line 16, in <module>
>     bot.listen(timeout=60)
>   File "build/bdist.linux-x86_64/egg/snapchat_bots/bot.py", line 65, in listen
>   File "examples/capturebot.py", line 6, in on_snap
>     snap.save()
>   File "build/bdist.linux-x86_64/egg/snapchat_bots/snap.py", line 52, in save
> NameError: global name 'filename' is not defined
>
> Possible fix: declare filename = default_filename_for_snap(snap)
>
> Thanks !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agermanidis/SnapchatBot/issues/31>.
>



-- 
Anastasis Germanidis
(860) 807-5860

**Comment by N07070** [comment]
fixed ! :smile: 

Thanks !
