### ISSUE TITLE
Error when calling 'snap.save()'

### ISSUE THREAD

**Issue by Jfach** [agermanidis/SnapchatBot#36]
I added the line 'snap.save()'  under the on_snap function's definition.

When I send my bot a snap, I get this error message:

Traceback (most recent call last):
  File "testbot.py", line 19, in <module>
    bot.listen(timeout=35)
  File "build\bdist.win-amd64\egg\snapchat_bots\bot.py", line 65, in listen
  File "testbot.py", line 6, in on_snap
    snap.save()
  File "build\bdist.win-amd64\egg\snapchat_bots\snap.py", line 52, in save
IOError: [Errno 22] invalid mode ('wb') or filename: u'.\\2015-3-12_16:54:22_jfachh.mp4'

**Comment by agermanidis** [comment]
Thanks. This seems to be related to allowed characters on windows pathnames
- i'll fix this later today by changing the filename format of snaps.

On Thu, Mar 12, 2015 at 4:59 PM, Jordan Facibene <notifications@github.com>
wrote:

> I added the line 'snap.save()' to under the on_snap function.
>
> When I send my bot a snap, I get this error message:
>
> Traceback (most recent call last):
> File "testbot.py", line 19, in
> bot.listen(timeout=35)
> File "build\bdist.win-amd64\egg\snapchat_bots\bot.py", line 65, in listen
> File "testbot.py", line 6, in on_snap
> snap.save()
> File "build\bdist.win-amd64\egg\snapchat_bots\snap.py", line 52, in save
> IOError: [Errno 22] invalid mode ('wb') or filename:
> u'.\2015-3-12_16:54:22_jfachh.mp4'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agermanidis/SnapchatBot/issues/36>.
>



-- 
Anastasis Germanidis
(860) 807-5860

**Comment by Jfach** [comment]
Thanks for the fast response! I did some digging around in snap.py. I think you may be correct, as I was able to successfully save by including "snap.jpg as the output_filename parameter. Looking forward to the fix, cheers!

**Comment by agermanidis** [comment]
You could try to make a pull request too if you'd like! Just edit the
snap.py source to remove the ":" characters from the output filename.

On Thu, Mar 12, 2015 at 5:12 PM, Jordan Facibene <notifications@github.com>
wrote:

> Thanks for the fast response! I did some digging around in snap.py. I
> think you may be correct, as I was able to successfully save by including
> "snap.jpg as the output_filename parameter. Looking forward to the fix,
> cheers!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agermanidis/SnapchatBot/issues/36#issuecomment-78619381>
> .
>



-- 
Anastasis Germanidis
(860) 807-5860
