### ISSUE TITLE
Bot won't post on storie

### ISSUE THREAD

**Issue by larserikfagernaes** [agermanidis/SnapchatBot#43]
Suddenly my bot stopped posting on story. The bot doesn't call the on_snap function it seems. Does annybody else have or know what causes this problem ?

**Comment by larserikfagernaes** [comment]
I get this error: 
"requests.exceptions.HTTPError: 401 Client Error: Unauthorized"

**Comment by N07070** [comment]
Please do a search before next time... 

It means your bot has been banned by snapchat. Go to snapchat.com/unlock to unlock it. 

Le 14 mars 2015 17:26:05 GMT+01:00, larserikfagernaes <notifications@github.com> a écrit :
>I get this error: 
>"requests.exceptions.HTTPError: 401 Client Error: Unauthorized"
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/agermanidis/SnapchatBot/issues/43#issuecomment-80561409

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
