### ISSUE TITLE
Loss of image quality

### ISSUE THREAD

**Issue by brandonthepvongsa** [agermanidis/SnapchatBot#5]
I forked this over a few days ago and I recall testing it and seeing the reflector bot sent back an image of approximately the same quality, but for some reason now the reflected image has a significant quality loss. Is this normal or am I doing something wrong?

**Comment by agermanidis** [comment]
Interesting, thanks. I'm almost certain I haven't changed any of the image processing code in the past few days but I'll look into it!

**Comment by brandonthepvongsa** [comment]
Yeah I'm looking into it and I really don't know what it is. 

1. I did a bit of testing, sent a snap from user A to user B and attempted to reflect that back. Loss of quality.

2. Sent a snap from A to B and viewed the snap using the original SnapChat software. No loss of quality.

3. Sent a snap from A to B and saved the snap locally after being process by SnapChatBot. Loss of quality. 

I assume it's all still working correctly (without a loss of quality) when you try to recreate the steps of simply using the reflectorbot?

**Comment by agermanidis** [comment]
Hey, can you pull the latest commit and try running the reflector bot again?

**Comment by agermanidis** [comment]
I think Snapchat changed something on their server code recently -- before there were black bars around snaps when I wasn't using a specific image size that I found through trial & error, but that doesn't seem to be the case anymore, so I started using a much larger one.

**Comment by krissrex** [comment]
I blamed some code about this. Seems to be an issue with image saving. Try this:
```python
im.save(f.name,'JPEG', quality=100)
```

So as a workaround before it is fixed, you can use:
```python
import tempfile
from snapchat_bots.constants import MEDIA_TYPE_IMAGE
from snapchat_bots import Snap
from PIL import Image

if snap.media_type is MEDIA_TYPE_IMAGE:
    im = Image.open(snap.file.name)
    f = tempfile.NamedTemporaryFile(suffix=".jpg", delete=False)
    im.save(f.name,'JPEG', quality=100)
    return Snap(path=f. name, media_type=MEDIA_TYPE_IMAGE, duration=10)
```

I could also note that duration does not seem to be set to 10 here, but rather 6. Possible bug?

**Comment by brandonthepvongsa** [comment]
Nice find!

**Comment by agermanidis** [comment]
I'm assuming has been fixed after image size / quality commits, let me know if it hasn't!
