### ISSUE TITLE
Insecure Platform Warning

### ISSUE THREAD

**Issue by mavieth** [agermanidis/SnapchatBot#53]
While running bot.listen() every request responds with this message.

Is anyone else having a similar issue? It is still fully functional.

[2015-03-22 22:04:18,923] "POST /bq/blob HTTP/1.1" 410 None
[2015-03-22 22:04:18,997] Starting new HTTPS connection (1): feelinsonice-hrd.appspot.com
/usr/local/lib/python2.7/dist-packages/requests-2.6.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

**Comment by mavieth** [comment]
This fixed it:

sudo pip install requests==2.5.3

**Comment by agermanidis** [comment]
Thanks, I made the change.

**Comment by Lukasa** [comment]
This is a *terrible* idea.

requests 2.5.3 contains a known security vulnerability, CVE 2015-2296, as noted in [the release notes](http://docs.python-requests.org/en/latest/community/updates/#id3). You should be bringing your pin up to at least 2.6.0.

**Comment by mavieth** [comment]
I was unaware. So it should be modified to:

sudo pip install requests==2.6.0

Thanks!

**Comment by JohnTroony** [comment]
What about  `pip install pyopenssl ndg-httpsclient pyasn1` ? I'm using these on an OpenSuse 13.2 install (64 bit) and there are no errors :P

**Comment by N07070** [comment]
The framework works for you ?

•

**Comment by JohnTroony** [comment]
@N07070 Maybe, I'm using `virtualenv`. Not really sure if other versions of these packages are installed, overriding my set up... I can copy my `pip.log` file on pastebin just in case you want to take a look.

**Comment by mavieth** [comment]
That would be awesome.

On Mon, Jul 6, 2015 at 3:25 PM, John Troony <notifications@github.com>
wrote:

> @N07070 <https://github.com/N07070> Maybe, I'm using virtualenv. Not
> really sure if other versions of these packages are installed, overriding
> my set up... I can copy my pip.log file on pastebin just in case you want
> to take a look.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agermanidis/SnapchatBot/issues/53#issuecomment-118969947>
> .
>



-- 
Michael Vieth
The Ohio State University
Computer Information Science
(614)-557-6952

**Comment by N07070** [comment]
Could you make a test with the latest version or/and provide a log of your install ?

Could you test a bot and say if it works ?

•

**Comment by N07070** [comment]
@JohnTroony Hey ? Did it work for you then ?
